//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
public class DmgBuff : Buff
{
		public DmgBuff (bool isGood, int duration, Character user) : base (isGood, duration, user)
		{
		
		}
	
		public override void calculate ()
		{
		
		}
		
		public int damageAdjustment ()
		{
				if (isGood) {
						return 23 / 20;
				} else {
						return 20 / 23;
				}
		}
}