//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
public class PAtkBuff : Buff
{
		public PAtkBuff (bool isGood, int duration, Character user) : base (isGood, duration, user)
		{

		}

		public override void calculate ()
		{
				if (isGood) {
						user.pAtk = user.pAtk * 3 / 2;
				} else {
						if (user.pAtk < 10) {
								user.pAtk = 0;
						} else {
								user.pAtk -= 10;
						}
				}
		}
}


