//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace AssemblyCSharp
{
		public class PDefBuff : Buff
		{
				public PDefBuff (bool _isGood, int duration) : base (_isGood, duration)
				{

				}

				public override void calculate ()
				{
						if (isGood) {
								user.pDef = user.pDef * 3 / 2;
						} else {
								if (user.pDef < 10) {
										user.pDef = 0;
								} else {
										user.pDef -= 10;
								}
						}
				}
		}
}

