//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		abstract public class Consumable : Item
		{
				public int APcost {
						get;
						set;
				}

				public int nbObjects {
						get;
						set;
				}


				public int[] effect {
						get;
						set;
		}

			public Consumable (): base ()
			{
				APcost = 0;
				nbObjects = 0;
				this.effect = new int[] {0,0,0,0,0,0};
			}

			public Consumable(int _APcost, int _nb,int _str, int _con, int _intel, int _wis, int _dex, int _health) :base(){
				this.APcost = _APcost;
				this.nbObjects = _nb;
				this.effect = new int[] {_str,_con,_intel,_wis,_dex,_health};
		}

			public void useOneItem(){
				this.nbObjects --;
			}



		}
}

