//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		abstract public class Equipment : Item
		{
				
		// gives the amounts of enhancements which are brought by the equipment 
		// in the orger : strength, constitution, intell, wisdom, dexterity, vitallity
		public int[] enhancements {
						get;
						set;
		}

		public Equipment(): base (){
			this.enhancements = new int[6]; 
		}

		public Equipment ( int[] _en) : base( _des)
		{
			this.enhancements = _en;
		}

		public Equipment(int st, int con, int intell, int wis, int dex, int vit): base( _des){

			this.enhancements = new int[]{st,con,intell,wis,dex,vit};
				}

		}
}

