//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	abstract public class Item
	{
			//Description of the item
			public string description {
				get;
				set;				
			}
				public Item ()
				{
					this.description = "";
				}
		public Item (string _des)
		{
			this.description = _des;
		}
	}
}

